services:
  timescale:
    image: timescale/timescaledb-postgis:2.15.0-pg15
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  backend:
    build: .
    volumes:
      - ./:/app
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - timescale
      - qdrant
